### ISSUE TITLE
Cannot reproduced the rest in test sets by using the model you trained.

### ISSUE THREAD

**Issue by probe2** [rishabhjoshi/DialoGraph_ICLR21#2]
Hi, 
I am trying to reproduce your results. I used your github code and the model you published, but when I used the graph model you published to conduct an experiment on the test set, I found that the  loss is 500 and the bleu score is also very low. According to the results stored in the graph.pkl you publish, there are only more than 70. What is the problem?

Thanks you very much for reading my letter~

**Comment by rishabhjoshi** [comment]
Hi, Please email me with all the steps you tried and check if the data you are using is correctly formatted. Try to run with the processed data I provided. We can set up a call if you're still having issues -- please email me.
